# Generated by Django 4.2.6 on 2023-10-11 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_user_auther_auther'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
